### ISSUE TITLE
MPI_THREAD_SERIALIZED and Elemental 0.84 crash immediately

### ISSUE THREAD

**Issue by naromero77** [m-a-d-n-e-s-s/madness#165]
This is how to reproduce the problem. I initially found the problem on BG/Q, but I can reproduce it on my Linux desktop.

Compile madness with:
--with-mpi-thread=serialized

as well as support for Elemental. Then run a moldft (e.g. 9 h2o molecules) calculation on four ranks. 
moldft crashes immediately in Elemental initialize. 
Abort(1) on node 3 (rank 3 in comm 1140850688): Fatal error in PMPI_Group_translate_ranks: Invalid rank, error s
tack:
PMPI_Group_translate_ranks(217): MPI_Group_translate_ranks(group=0x88000001, n=4, ranks1=0x19c7acc0f0, group=0x8
8000000, ranks2=0x19c7acc0a0) failed
PMPI_Group_translate_ranks(188): Invalid rank has value 3 but must be nonnegative and less than 3
Abort(1) on node 0 (rank 0 in comm 1140850688): Fatal error in PMPI_Group_translate_ranks: Invalid rank, error s
tack:
PMPI_Group_translate_ranks(217): MPI_Group_translate_ranks(group=0x88000001, n=4, ranks1=0x19c7acc0b0, group=0x8
8000000, ranks2=0x19c7acc0a0) failed
PMPI_Group_translate_ranks(188): Invalid rank has value 2 but must be nonnegative and less than 2
Abort(1) on node 2 (rank 2 in comm 1140850688): Fatal error in PMPI_Group_translate_ranks: Invalid rank, error s
tack:
PMPI_Group_translate_ranks(217): MPI_Group_translate_ranks(group=0x88000001, n=4, ranks1=0x19c7acc0f0, group=0x8
8000000, ranks2=0x19c7acc0a0) failed
PMPI_Group_translate_ranks(188): Invalid rank has value 2 but must be nonnegative and less than 2
Abort(1) on node 1 (rank 1 in comm 1140850688): Fatal error in PMPI_Group_translate_ranks: Invalid rank, error s
tack:
PMPI_Group_translate_ranks(217): MPI_Group_translate_ranks(group=0x88000001, n=4, ranks1=0x19c7acc0e0, group=0x8
8000000, ranks2=0x19c7acc0a0) failed
PMPI_Group_translate_ranks(188): Invalid rank has value 2 but must be nonnegative and less than 2
Abort(1) on node 3 (rank 3 in comm 1140850688): Fatal error in MPI_Allreduce: Message truncated, error stack:
MPI_Allreduce(861).......: MPI_Allreduce(sbuf=0x1dbfff5638, rbuf=0x1dbfff5648, count=1, MPI_DOUBLE_INT, MPI_MINL
OC, MPI_COMM_WORLD) failed
MPIR_Allreduce_impl(719).: 
MPIR_Allreduce_intra(362): 
MPIC_Sendrecv(186).......: 
MPIDI_Buffer_copy(73)....: Message truncated; 260 bytes received but buffer size is 12
MPIR_Allreduce_intra(362): 
MPIC_Sendrecv(186).......: 
MPIDI_Buffer_copy(73)....: Message truncated; 260 bytes received but buffer size is 12
Abort(1) on node 0 (rank 0 in comm 1140850688): Fatal error in MPI_Allreduce: Message truncated, error stack:
MPI_Allreduce(861).......: MPI_Allreduce(sbuf=0x1dbfff5638, rbuf=0x1dbfff5648, count=1, MPI_DOUBLE_INT, MPI_MINL
OC, MPI_COMM_WORLD) failed
MPIR_Allreduce_impl(719).: 
MPIR_Allreduce_intra(362): 
MPIC_Sendrecv(186).......:

If you use MPI_THREAD_MULTIPLE with Elemental, it runs correctly. If you use MPI_THREAD_SERIALIZED without Elemental, it runs correctly. So it seems the problem is either in Elemental itself, or our use of it.

**Comment by jeffhammond** [comment]
This is a known issue, although perhaps not widely known.  In order for MADNESS to interoperate with libraries that call MPI, it must use MPI_THREAD_MULTIPLE.  The reason is that MADNESS will call MPI from a thread while such libraries are calling MPI from the main thread, which violates the MPI_THREAD_SERIALIZED model.

I wrote about this exact issue in [Challenges for Interoperability of Runtime Systems in Scientific Applications](https://www.ieeetcsc.org/activities/blog/challenges_for_interoperability_of_runtime_systems_in_scientific_applications).

There is really no practical solution besides MPI_THREAD_MULTIPLE here.  Trying to use a unified mutex across MADNESS and Elemental will lead to spaghetti code.

Because Blue Gene/Q has arguably the best MPI_THREAD_MULTIPLE support around, I don't know why you don't use that.

We should put in a configure test that forces users to use MPI_THREAD_MULTIPLE when they use Elemental.  This is the only action we should take here.

**Comment by naromero77** [comment]
I use MPI_THREAD_MULTIPLE on BG/Q 99% of the time. I was actually trying to debug something else, which is why I was experimenting with MPI_THREAD_SERIALIZED.

The right solution is to force configure to use MPI_THREAD_MULTIPLE if Elemental is used.

Thanks for the reference to the web article.
