### ISSUE TITLE
Recent Travis CI build failures

### ISSUE THREAD

**Issue by bsundahl** [m-a-d-n-e-s-s/madness#294]
There are a number of Travis CI builds using clang++ that are failing across all pull requests made since early August. The failure is due to Travis CI not finding the MPI libraries. 

Could someone with Travis CI knowledge take a look?

**Comment by fbischoff** [comment]
As Bryan noticed some time ago we should try to make the Travis CI test work again or otherwise switch them off.

Also I noticed the following issues:

 1) In OSX the rpaths are not set correctly, e.g. I can’t run anything using nohup nor can’t I run the test suite. The osx-toolchain does not solve the problem, and I didn’t find anything that would work on my laptop.
 
 2) If i run the generic-mkl-tbb.cmake  toolchain MKL is not found unless it’s in the standard location, even if I specify -D MKL_ROOT_DIR.

Mayby someone has any ideas on this?

Best,
Florian




Florian Bischoff
Humboldt-Universitaet zu Berlin, Institut fuer Chemie
Unter den Linden 6, 10099 Berlin
phone: +49-30-2093-7140
florian.bischoff@hu-berlin.de
